general {
    lock_cmd = pidof hyprlock || hyprlock       # Evita abrir múltiples instancias
    before_sleep_cmd = loginctl lock-session    # Bloquea antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Enciende la pantalla al despertar
}

listener {
    timeout = 300                               # 5 minutos de inactividad
    on-timeout = hyprlock          # Bloquea la sesión
}

listener {
    timeout = 330                               # 5.5 minutos
    on-timeout = hyprctl dispatch dpms off      # Apaga los monitores
    on-resume = hyprctl dispatch dpms on        # Enciende los monitores al detectar actividad
}

