background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 1 

    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(df970dff)
    inner_color = rgb(101010)
    font_color = rgb(cdcde0)

    fade_on_empty = false
    rounding = 12

    position = 0, -20
    halign = center
    valign = center

    placeholder_text = Contraseña
    fail_text = Contraseña Incorrecta
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"

    color = rgba(255,255,255,1)
    font_size = 80
    font_family = Sans

    position = 0, 120
    halign = center
    valign = center
}
