general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Bloquear sesión tras 2 min
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

# Apagar pantallas tras 5 min
listener {
    timeout = 300 
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspender tras 15 min
listener {
    timeout = 900 
    on-timeout = sh -c '[ "$(cat /sys/class/power_supply/AC/online)" = "0" ] && systemctl suspend'
}
