splash = false
ipc = true

wallpaper {
    monitor =
    #path = /home/rlopez/Pictures/wallpaper1.jpg
    #path = /usr/share/hypr/wall0.png
    path = /home/rlopez/Pictures/wallpaper2.jpg
    fit_mode = cover
}
